# -u kodi does not work here, and ansible devs just close the thread brutally without explaination

# ansible-playbook -i hosts -k -K -e 'ansible_user=kodi' 01-init.yaml

- hosts: all
  become: yes
  tasks:
    - name: create the 'ubuntu' user
      user: name=ubuntu append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'ubuntu' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: user=ubuntu key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

# Common depends
    - name: install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

# I  need to add this (stevek)
    - name: enable docker servive
      service: name=docker enabled=yes state=started

    - name: install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present

    # stevek - gpg-agent required for apt-key mod. curl required for k3s fetching install script
    - apt:
        name: ['gpg-agent','curl']
        state: present
