# https://rancher.com/docs/k3s/latest/en/quick-start/

- hosts: master
  become: yes
  tasks:
    - name: Fetch and run the k3s deployment script from get.k3s.io
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        chdir: $HOME
        creates: /etc/rancher/k3s/k3s.yaml

    - name: Get the K3S_TOKEN
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: get_k3s_token_out

    - set_fact:
        k3s_token: "{{ get_k3s_token_out.stdout }}"

- hosts: workers
  become: yes
  tasks:
    - name: Fetch and run the k3s deployment script from get.k3s.io for workers
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['master']['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars['master'].k3s_token }} sh -
